// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

// @ts-nocheck
// This file cannot be converted to TypeScript easily

// Provides consistency and styling to elements generated by our Markdown pages

import { MDXProvider } from "@mdx-js/react";

// Chakra UI, icons, and other design imports
import { Heading, Text, Divider } from "@chakra-ui/react";

const componentOverrides = {
  h1: (props) => <Heading size="xl" mb={5} {...props} />,
  h2: (props) => <Heading size="md" mb={2} {...props} />,
  h3: (props) => <Text textStyle="miniHeading" as="h6" {...props} />,
  p: (props) => <Text {...props} my={2} />,
  hr: (props) => <Divider {...props} my={5} />,
};

export default function MDXProviderComponent({ children }) {
  return <MDXProvider components={componentOverrides}>{children}</MDXProvider>;
}
