name: Lighthouse Performance CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit Application Performance using Lighthouse CI
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            http://localhost:3000
            http://localhost:3000/browse
            http://localhost:3000/browse/demo
          budgetPath: ../.github/ciconfig/lighthouse/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
