name: Lighthouse Desktop CI
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print System Specification
        run: node -p 'os.cpus()'

      - name: Set Persistent Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            http:localhost:3000
            http:localhost:3000/browse
            http:localhost:3000/browse/elementary
            http:localhost:3000/search
            http:localhost:3000/privacy
          runs: 1
          configPath: ".github/ciconfig/lighthouse/desktop-config.json"
          uploadArtifacts: true
          build: npm run build
          start: npm run start
