name: Lighthouse Performance Testing
on: [push]

jobs:
  lhci:
    name: Lighthouse CI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Run Lighthouse CI Checks
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
