name: Lighthouse Desktop CI

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://www.ulosino.com/
            https://www.ulosino.com/browse/
            https://www.ulosino.com/browse/elementary
            https://www.ulosino.com/search
            https://www.ulosino.com/privacy
          runs: 1
          configPath: ".github/ciconfig/lighthouse/desktop-config.json"
          uploadArtifacts: true
